[package]
name = "AuthApi"
version = "0.1.0"
edition = "2021"

[dependencies]

poem = { version = "3.1.12", features = ["session"] }
tokio = { version = "1", features = ["full"] }
des = "0.8"
cipher = "0.4"
hex = "0.4"
serde = { version = "1.0", features = ["derive"] }
